type IGetCurrentUserActionName =
  | "GET_CURRENT_USER"
  | "GET_CURRENT_USER_SUCCESS"
  | "GET_CURRENT_USER_FAILURE";

const GET_CURRENT_USER: IGetCurrentUserActionName = "GET_CURRENT_USER";
const GET_CURRENT_USER_SUCCESS: IGetCurrentUserActionName =
  "GET_CURRENT_USER_SUCCESS";
const GET_CURRENT_USER_FAILURE: IGetCurrentUserActionName =
  "GET_CURRENT_USER_FAILURE";

export {
  IGetCurrentUserActionName,
  GET_CURRENT_USER,
  GET_CURRENT_USER_SUCCESS,
  GET_CURRENT_USER_FAILURE,
};
